"use client";
import { useState } from "react";
import type { FormEvent } from "react";
import { Button } from "@/app/components/ui/Button";
import { EmptyState } from "@/app/components/ui/DataState";
import { Modal } from "@/app/components/ui/Modal";
import { FormField, SelectField } from "@/app/components/ui/FormField";
import { saveFinanceCatalogItem } from "../finance.mutations";
import { normalizeMoneyInput } from "../finance.money";
import { useAsyncAction } from "@/app/hooks/useAsyncAction";
import type { FinanceLookup, FinanceStoredEnvironment } from "../types";

type Props={title:string;description:string;table:string;items:FinanceLookup[];environment:FinanceStoredEnvironment;canManage:boolean;onReload:()=>void;typeOptions?:Array<[string,string]>;accounts?:FinanceLookup[]};

export function FinanceCatalogManager({title,description,table,items,environment,canManage,onReload,typeOptions,accounts=[]}:Props){
 const[open,setOpen]=useState(false);const[selected,setSelected]=useState<FinanceLookup|null>(null);const action=useAsyncAction();
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const payload:Record<string,unknown>={id:selected?.id,environment,name:String(form.get("name")||"").trim(),active:form.get("active")==="on"};
  if(typeOptions)payload.type=String(form.get("type")||"")||null;
  if(table==="financial_categories"){payload.entry_type=String(form.get("entry_type")||"expense");payload.parent_id=String(form.get("parent_id")||"")||null;payload.color=String(form.get("color")||"")||null;payload.code=String(form.get("code")||"")||null}
  if(table==="financial_accounts"){payload.institution=String(form.get("institution")||"")||null;payload.branch=String(form.get("branch")||"")||null;payload.account_number_masked=String(form.get("account_number_masked")||"")||null;payload.opening_balance=normalizeMoneyInput(String(form.get("opening_balance")||"0"));payload.opening_balance_date=String(form.get("opening_balance_date")||new Date().toISOString().slice(0,10))}
  if(table==="financial_cards"){payload.brand=String(form.get("brand")||"")||null;payload.last_four_digits=String(form.get("last_four_digits")||"").replace(/\D/g,"").slice(-4)||null;payload.closing_day=Number(form.get("closing_day")||1);payload.due_day=Number(form.get("due_day")||10);payload.limit_amount=normalizeMoneyInput(String(form.get("limit_amount")||"0"));payload.account_id=String(form.get("account_id")||"")||null}
  if(table==="financial_suppliers"){payload.document=String(form.get("document")||"")||null;payload.phone=String(form.get("phone")||"")||null;payload.email=String(form.get("email")||"")||null}
  if(table==="financial_cost_centers")payload.code=String(form.get("code")||"")||null;
  if(table==="financial_templates"){payload.entry_type=String(form.get("entry_type")||"expense");payload.description=String(form.get("description")||"")||null;payload.suggested_amount=normalizeMoneyInput(String(form.get("suggested_amount")||"0"));payload.frequency=String(form.get("frequency")||"")||null;payload.due_day=Number(form.get("due_day")||0)||null}
  const result=await action.run(()=>saveFinanceCatalogItem(table,payload),selected?"Cadastro atualizado.":"Cadastro criado.");if(result.ok){setOpen(false);setSelected(null);onReload()}}
 const parentOptions=items.filter((item)=>item.id!==selected?.id&&!item.parent_id);
 return <section className="cs-finance-catalog"><header><div><h2>{title}</h2><p>{description}</p></div>{canManage&&<Button variant="primary" onClick={()=>{setSelected(null);setOpen(true)}}>Novo</Button>}</header>{items.length===0?<EmptyState title={`Nenhum cadastro em ${title.toLowerCase()}`} description="Crie o primeiro registro para este ambiente."/>:<div className="cs-finance-catalog-grid">{items.map((item)=><article className="cs-card" key={item.id}><span>{item.type||item.entry_type||"Cadastro"}</span><strong>{item.name}</strong><small>{item.active===false?"Inativo":"Ativo"}</small>{canManage&&<Button variant="text" onClick={()=>{setSelected(item);setOpen(true)}}>Editar</Button>}</article>)}</div>}{open&&<Modal title={selected?`Editar ${title}`:`Novo em ${title}`} onClose={()=>setOpen(false)}><form className="cs-form-grid" onSubmit={submit}><FormField className="cs-span-2" label="Nome" name="name" defaultValue={selected?.name??""} required/>{typeOptions&&<SelectField label="Tipo" name="type" defaultValue={selected?.type??typeOptions[0]?.[0]}>{typeOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</SelectField>}
 {table==="financial_categories"&&<><SelectField label="Natureza" name="entry_type" defaultValue={selected?.entry_type??"expense"}><option value="income">Receita</option><option value="expense">Despesa</option></SelectField><SelectField label="Categoria principal" name="parent_id" defaultValue={selected?.parent_id??""}><option value="">Categoria principal</option>{parentOptions.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</SelectField><FormField label="Código" name="code" defaultValue={selected?.code??""}/><FormField label="Cor" name="color" type="color" defaultValue={selected?.color??"#8e7c75"}/></>}
 {table==="financial_accounts"&&<><FormField label="Instituição" name="institution" defaultValue={selected?.institution??""}/><FormField label="Agência" name="branch" defaultValue={selected?.branch??""}/><FormField label="Identificação mascarada" name="account_number_masked" defaultValue={selected?.account_number_masked??""}/><FormField label="Saldo inicial" name="opening_balance" inputMode="decimal" defaultValue={selected?.opening_balance??"0,00"}/><FormField label="Data do saldo inicial" name="opening_balance_date" type="date" defaultValue={selected?.opening_balance_date??new Date().toISOString().slice(0,10)}/></>}
 {table==="financial_cards"&&<><FormField label="Bandeira" name="brand" defaultValue={selected?.brand??""}/><FormField label="Últimos 4 dígitos" name="last_four_digits" inputMode="numeric" maxLength={4} defaultValue={selected?.last_four_digits??""}/><FormField label="Dia de fechamento" name="closing_day" type="number" min="1" max="31" defaultValue={selected?.closing_day??1}/><FormField label="Dia de vencimento" name="due_day" type="number" min="1" max="31" defaultValue={selected?.due_day??10}/><FormField label="Limite" name="limit_amount" inputMode="decimal" defaultValue={selected?.limit_amount??"0,00"}/><SelectField label="Conta para pagamento" name="account_id" defaultValue={selected?.account_id??""}><option value="">Sem conta</option>{accounts.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</SelectField></>}
 {table==="financial_suppliers"&&<><FormField label="CPF/CNPJ" name="document" defaultValue={selected?.document??""}/><FormField label="Telefone" name="phone" defaultValue={selected?.phone??""}/><FormField className="cs-span-2" label="E-mail" name="email" type="email" defaultValue={selected?.email??""}/></>}
 {table==="financial_cost_centers"&&<FormField label="Código" name="code" defaultValue={selected?.code??""}/>} 
 {table==="financial_templates"&&<><SelectField label="Natureza" name="entry_type" defaultValue={selected?.entry_type??"expense"}><option value="income">Receita</option><option value="expense">Despesa</option></SelectField><FormField className="cs-span-2" label="Descrição padrão" name="description" defaultValue={selected?.description??""}/><FormField label="Valor sugerido" name="suggested_amount" inputMode="decimal" defaultValue={selected?.suggested_amount??"0,00"}/><SelectField label="Periodicidade" name="frequency" defaultValue={selected?.frequency??""}><option value="">Sem periodicidade</option><option value="weekly">Semanal</option><option value="monthly">Mensal</option><option value="quarterly">Trimestral</option><option value="yearly">Anual</option></SelectField><FormField label="Dia do vencimento" name="due_day" type="number" min="1" max="31" defaultValue={selected?.due_day??""}/></>}
 <label className="cs-check-row"><input type="checkbox" name="active" defaultChecked={selected?.active!==false}/><span>Ativo</span></label><div className="cs-form-actions"><Button type="button" onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="primary" loading={action.pending}>Salvar</Button></div></form></Modal>}</section>
}
