import type { ReportDefinition } from "./types";
const base = (key:string,label:string,format?:"date"|"datetime"|"money"|"number"|"percent") => ({key,label,format});
export const reportCatalog: ReportDefinition[] = [
  {code:"projects_by_stage",title:"Projetos por etapa",description:"Distribuição e detalhamento dos projetos acessíveis por etapa.",group:"Projetos",columns:[base("stage_name","Etapa"),base("total","Projetos","number"),base("late","Atrasados","number")]},
  {code:"projects_by_status",title:"Projetos por status",description:"Projetos agrupados pela situação atual.",group:"Projetos",columns:[base("status_name","Status"),base("total","Projetos","number"),base("late","Atrasados","number")]},
  {code:"projects_by_responsible",title:"Projetos por responsável",description:"Carga de projetos e atrasos por responsável.",group:"Projetos",columns:[base("responsible_name","Responsável"),base("total","Projetos","number"),base("late","Atrasados","number")]},
  {code:"projects_overdue",title:"Prazos vencidos",description:"Projetos ativos cujo prazo principal já venceu.",group:"Projetos",columns:[base("code","Código"),base("name","Projeto"),base("client_name","Cliente"),base("responsible_name","Responsável"),base("stage_name","Etapa"),base("main_deadline","Prazo","date"),base("days_late","Dias em atraso","number")]},
  {code:"projects_upcoming",title:"Prazos futuros",description:"Projetos com prazo no período selecionado.",group:"Projetos",columns:[base("code","Código"),base("name","Projeto"),base("client_name","Cliente"),base("responsible_name","Responsável"),base("main_deadline","Prazo","date"),base("days_until","Dias restantes","number")]},
  {code:"activities_by_status",title:"Atividades por status",description:"Distribuição das atividades acessíveis por status.",group:"Atividades",columns:[base("status_name","Status"),base("total","Atividades","number"),base("overdue","Atrasadas","number")]},
  {code:"activities_by_responsible",title:"Atividades por responsável",description:"Carga operacional por responsável.",group:"Atividades",columns:[base("responsible_name","Responsável"),base("total","Atividades","number"),base("completed","Concluídas","number"),base("overdue","Atrasadas","number")]},
  {code:"activities_overdue",title:"Atividades atrasadas",description:"Atividades não concluídas com prazo vencido.",group:"Atividades",columns:[base("title","Atividade"),base("project_name","Projeto"),base("client_name","Cliente"),base("responsible_name","Responsável"),base("due_at","Prazo","datetime"),base("days_late","Dias em atraso","number")]},
  {code:"checklists",title:"Checklists",description:"Conclusão, pendências obrigatórias e dispensas por projeto.",group:"Operacional",columns:[base("project_code","Código"),base("project_name","Projeto"),base("total_items","Itens","number"),base("completed_items","Concluídos","number"),base("required_pending","Obrigatórios pendentes","number"),base("progress","Progresso","percent")]},
  {code:"clients",title:"Clientes",description:"Clientes, projetos, atividades e movimentações recentes.",group:"Clientes",columns:[base("name","Cliente"),base("relationship_status","Relacionamento"),base("projects","Projetos","number"),base("activities","Atividades","number"),base("last_movement","Última movimentação","datetime")]},
  {code:"history",title:"Histórico de alterações",description:"Auditoria por módulo, autor, ação e registro.",group:"Auditoria",columns:[base("created_at","Data","datetime"),base("module","Módulo"),base("action","Ação"),base("actor_name","Autor"),base("description","Descrição"),base("record_id","Registro")]},
  {code:"agenda",title:"Agenda",description:"Compromissos por tipo, responsável e situação.",group:"Agenda",columns:[base("starts_at","Início","datetime"),base("title","Compromisso"),base("item_type","Tipo"),base("status","Status"),base("responsible_name","Responsável"),base("project_name","Projeto"),base("client_name","Cliente")]},
  {code:"productivity",title:"Produtividade",description:"Conclusões operacionais por responsável no período.",group:"Operacional",columns:[base("responsible_name","Responsável"),base("activities_completed","Atividades concluídas","number"),base("projects_completed","Projetos concluídos","number"),base("events_completed","Compromissos concluídos","number"),base("checklist_items_completed","Checklist concluído","number"),base("score","Volume operacional","number")]},
  {code:"receivables",title:"Contas a receber",description:"Receitas profissionais em aberto e vencidas.",group:"Financeiro",financial:true,columns:[base("description","Descrição"),base("client_name","Cliente"),base("project_name","Projeto"),base("due_date","Vencimento","date"),base("open_amount","Em aberto","money"),base("effective_status","Status")]},
  {code:"payables",title:"Contas a pagar",description:"Despesas profissionais em aberto e vencidas.",group:"Financeiro",financial:true,columns:[base("description","Descrição"),base("supplier_name","Fornecedor"),base("due_date","Vencimento","date"),base("open_amount","Em aberto","money"),base("effective_status","Status")]},
];
export function reportByCode(code:string){return reportCatalog.find((item)=>item.code===code)??reportCatalog[0]}
