"use client";
import { useCallback,useMemo,useState } from "react";
import { ModuleFrame } from "@/app/components/ui/ModuleFrame";
import { LoadingState,ErrorState,EmptyState } from "@/app/components/ui/DataState";
import { useModuleData } from "@/app/hooks/useModuleData";
import { usePermissions } from "@/app/hooks/usePermissions";
import { reportCatalog,reportByCode } from "./report-catalog";
import { defaultReportFilters,loadReport,loadReportOptions } from "./reports.service";
import { ReportCatalog } from "./ReportCatalog";
import { ReportFilters } from "./ReportFilters";
import { ReportTable } from "./ReportTable";
import { ReportChart } from "./ReportChart";
import { ReportExportActions } from "./ReportExportActions";
import type { ReportCode } from "./types";
export function ReportsWorkspace(){const{can}=usePermissions();const canFinancial=can("reports","view_values")&&can("finance_professional","view_values");const visibleCatalog=useMemo(()=>reportCatalog.filter((item)=>!item.financial||canFinancial),[canFinancial]);const[selected,setSelected]=useState<ReportCode>(visibleCatalog[0]?.code??"projects_by_stage");const[draft,setDraft]=useState(defaultReportFilters);const[filters,setFilters]=useState(draft);const[page,setPage]=useState(0);const definition=reportByCode(selected);const optionsLoader=useCallback(()=>loadReportOptions(),[]);const{data:options}=useModuleData(optionsLoader,{projects:[],clients:[],responsible:[],stages:[],statuses:[],modules:[]});const loader=useCallback(()=>loadReport(selected,filters,page,100),[selected,filters,page]);const{data,loading,error,reload}=useModuleData(loader,null);function choose(code:ReportCode){setSelected(code);setPage(0)}return <ModuleFrame title="Relatórios" subtitle="Relatórios operacionais filtrados pelo escopo e pelas permissões do usuário"><div className="cs-reports-workspace"><ReportCatalog items={visibleCatalog} selected={selected} onSelect={choose}/><main className="cs-report-content"><header className="cs-report-header"><div><h2>{definition.title}</h2><p>{definition.description}</p></div>{data&&<ReportExportActions definition={definition} filters={filters} rows={data.rows} canExport={can("reports","export")}/>}</header><ReportFilters value={draft} options={options} onChange={setDraft} onApply={()=>{setFilters(draft);setPage(0)}} onReset={()=>{const next=defaultReportFilters();setDraft(next);setFilters(next);setPage(0)}}/>{error&&<ErrorState message={error} onRetry={()=>void reload()}/>} {loading||!data?<LoadingState/>:data.rows.length===0?<EmptyState title="Nenhum registro" description="Os filtros selecionados não retornaram dados autorizados."/>:<><section className="cs-report-summary"><article><span>Registros</span><strong>{data.total}</strong></article>{Object.entries(data.summary).slice(0,4).map(([key,value])=><article key={key}><span>{key.replaceAll("_"," ")}</span><strong>{String(value)}</strong></article>)}</section><section className="cs-card"><h3>Visão gráfica</h3><ReportChart items={data.chart}/></section><ReportTable definition={definition} rows={data.rows}/><footer className="cs-pagination"><button disabled={page===0} onClick={()=>setPage(Math.max(0,page-1))}>Anterior</button><span>Página {page+1}</span><button disabled={(page+1)*100>=data.total} onClick={()=>setPage(page+1)}>Próxima</button></footer></>}</main></div></ModuleFrame>}
