"use client";
import { useId, useRef } from "react";
import type { FormEvent } from "react";
import { Button } from "@/app/components/ui/Button";
import { FormField, SelectField } from "@/app/components/ui/FormField";
import { useBodyScrollLock } from "@/app/hooks/useBodyScrollLock";
import { useFocusTrap } from "@/app/components/a11y/FocusTrap";
import { formatMoney, normalizeMoneyInput } from "./finance.money";
import type { FinanceEntryRow, FinancePaymentInput, FinanceWorkspaceOptions } from "./types";

export function FinancePaymentDrawer({entry,options,pending,canViewValues,onClose,onSave}:{entry:FinanceEntryRow;options:FinanceWorkspaceOptions;pending:boolean;canViewValues:boolean;onClose:()=>void;onSave:(input:FinancePaymentInput)=>void}){
 const dialogRef=useRef<HTMLElement>(null);const titleId=useId();useBodyScrollLock(true);useFocusTrap(dialogRef,onClose);
 const isIncome=entry.entry_type==="income";
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);onSave({entry_id:entry.id,amount:normalizeMoneyInput(String(form.get("amount")||"0")),paid_at:new Date(`${String(form.get("paid_at"))}T12:00:00-04:00`).toISOString(),account_id:String(form.get("account_id")||"")||null,payment_method_id:String(form.get("payment_method_id")||"")||null,discount_amount:normalizeMoneyInput(String(form.get("discount_amount")||"0")),interest_amount:normalizeMoneyInput(String(form.get("interest_amount")||"0")),fine_amount:normalizeMoneyInput(String(form.get("fine_amount")||"0")),document_number:String(form.get("document_number")||"").trim()||null,notes:String(form.get("notes")||"").trim()||null})}
 return <div className="cs-drawer-backdrop" role="presentation" onMouseDown={onClose}><aside ref={dialogRef} className="cs-finance-payment-drawer" role="dialog" aria-modal="true" aria-labelledby={titleId} tabIndex={-1} onMouseDown={(event)=>event.stopPropagation()}><header className="cs-drawer-header"><div><small>{isIncome?"Recebimento total ou parcial":"Pagamento total ou parcial"}</small><h2 id={titleId}>{entry.description}</h2></div><button type="button" aria-label="Fechar baixa financeira" onClick={onClose}>×</button></header><form className="cs-drawer-body cs-finance-entry-form" onSubmit={submit}><article className="cs-finance-payment-summary"><span>Valor em aberto</span><strong>{formatMoney(entry.open_amount,canViewValues)}</strong></article><FormField label={isIncome?"Valor recebido":"Valor pago"} name="amount" defaultValue={entry.open_amount} max={entry.open_amount} inputMode="decimal" required/><FormField label={isIncome?"Data do recebimento":"Data do pagamento"} name="paid_at" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/><FormField label="Desconto" name="discount_amount" defaultValue="0,00" inputMode="decimal"/><FormField label="Juros" name="interest_amount" defaultValue="0,00" inputMode="decimal"/><FormField label="Multa" name="fine_amount" defaultValue="0,00" inputMode="decimal"/><SelectField label={isIncome?"Conta de entrada":"Conta de saída"} name="account_id" defaultValue={entry.account_id??options.accounts[0]?.id??""} required><option value="">Selecione a conta</option>{options.accounts.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</SelectField><SelectField label="Forma" name="payment_method_id" defaultValue={entry.payment_method_id??""}><option value="">Não informada</option>{options.payment_methods.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</SelectField><FormField label="Documento/comprovante" name="document_number"/><label className="cs-span-2"><span>Observações</span><textarea name="notes" rows={3}/></label><div className="cs-form-actions"><Button type="button" onClick={onClose}>Cancelar</Button><Button variant="primary" loading={pending}>{isIncome?"Confirmar recebimento":"Confirmar pagamento"}</Button></div></form></aside></div>
}
