"use client";
import { useId, useRef } from "react";
import type { FormEvent } from "react";
import { Button } from "@/app/components/ui/Button";
import { FormField, SelectField } from "@/app/components/ui/FormField";
import { useBodyScrollLock } from "@/app/hooks/useBodyScrollLock";
import { useFocusTrap } from "@/app/components/a11y/FocusTrap";
import { normalizeMoneyInput } from "./finance.money";
import type { FinanceStoredEnvironment, FinanceTransferInput, FinanceWorkspaceOptions } from "./types";
export function FinanceTransferDrawer({environment,options,pending,onClose,onSave}:{environment:FinanceStoredEnvironment;options:FinanceWorkspaceOptions;pending:boolean;onClose:()=>void;onSave:(input:FinanceTransferInput)=>void}){
 const dialogRef=useRef<HTMLElement>(null);const titleId=useId();useBodyScrollLock(true);useFocusTrap(dialogRef,onClose);
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);onSave({environment,transfer_type:String(form.get("transfer_type")),source_account_id:String(form.get("source_account_id")),destination_account_id:String(form.get("destination_account_id")),amount:normalizeMoneyInput(String(form.get("amount")||"0")),transfer_date:String(form.get("transfer_date")),description:String(form.get("description")||"").trim(),notes:String(form.get("notes")||"").trim()||null})}
 return <div className="cs-drawer-backdrop" role="presentation" onMouseDown={onClose}><aside ref={dialogRef} className="cs-finance-payment-drawer" role="dialog" aria-modal="true" aria-labelledby={titleId} tabIndex={-1} onMouseDown={(event)=>event.stopPropagation()}><header className="cs-drawer-header"><div><small>Movimento entre contas</small><h2 id={titleId}>Nova transferência</h2></div><button type="button" aria-label="Fechar transferência" onClick={onClose}>×</button></header><form className="cs-drawer-body cs-finance-entry-form" onSubmit={submit}><SelectField label="Tipo" name="transfer_type"><option value="internal_transfer">Transferência entre contas</option>{environment==="professional"&&<><option value="capital_contribution">Aporte para CNPJ</option><option value="withdrawal">Retirada</option><option value="pro_labore">Pró-labore</option><option value="profit_distribution">Distribuição de lucros</option></>}</SelectField><FormField label="Data" name="transfer_date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/><SelectField label="Conta de origem" name="source_account_id" required><option value="">Selecione</option>{options.accounts.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</SelectField><SelectField label="Conta de destino" name="destination_account_id" required><option value="">Selecione</option>{options.accounts.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</SelectField><FormField label="Valor" name="amount" inputMode="decimal" required/><FormField label="Descrição" name="description" required/><label className="cs-span-2"><span>Observações</span><textarea name="notes" rows={3}/></label><div className="cs-form-actions"><Button type="button" onClick={onClose}>Cancelar</Button><Button variant="primary" loading={pending}>Salvar transferência</Button></div></form></aside></div>
}
