"use client";
import { useState } from "react";
import { Button } from "@/app/components/ui/Button";
import type { ActivityNoteBlock, ActivityNoteBlockType, ActivityNoteDocument } from "@/app/features/activities/types";

const labels:Record<ActivityNoteBlockType,string>={heading:"Título",paragraph:"Parágrafo",bulleted_list:"Lista",numbered_list:"Lista numerada",checklist:"Checklist",link:"Link",image:"Imagem",file:"Arquivo",highlight:"Destaque"};
function newBlock(type:ActivityNoteBlockType):ActivityNoteBlock{return{id:crypto.randomUUID(),type,text:"",checked:false,url:""}}
export function ActivityNotesEditor({value,canEdit,onSave,pending}:{value:ActivityNoteDocument;canEdit:boolean;onSave:(value:ActivityNoteDocument)=>void;pending:boolean}){
 const[document,setDocument]=useState<ActivityNoteDocument>(value?.version===1?value:{version:1,blocks:[]});
 function update(id:string,patch:Partial<ActivityNoteBlock>){setDocument((current)=>({...current,blocks:current.blocks.map((block)=>block.id===id?{...block,...patch}:block)}))}
 function remove(id:string){setDocument((current)=>({...current,blocks:current.blocks.filter((block)=>block.id!==id)}))}
 function move(id:string,direction:number){setDocument((current)=>{const blocks=[...current.blocks];const index=blocks.findIndex((block)=>block.id===id);const target=index+direction;if(index<0||target<0||target>=blocks.length)return current;[blocks[index],blocks[target]]=[blocks[target],blocks[index]];return{...current,blocks}})}
 return <section className="cs-notes-editor"><header><div><h3>Observações</h3><p>Conteúdo estruturado, separado dos comentários.</p></div>{canEdit&&<Button variant="primary" loading={pending} onClick={()=>onSave(document)}>Salvar observações</Button>}</header>{document.blocks.length===0&&<p className="cs-empty-note">Nenhuma observação estruturada.</p>}<div className="cs-note-blocks">{document.blocks.map((block,index)=><article key={block.id} className={`cs-note-block type-${block.type}`}><div className="cs-note-block-toolbar"><select disabled={!canEdit} value={block.type} onChange={(e)=>update(block.id,{type:e.target.value as ActivityNoteBlockType})}>{Object.entries(labels).map(([type,label])=><option key={type} value={type}>{label}</option>)}</select>{canEdit&&<><button type="button" disabled={index===0} onClick={()=>move(block.id,-1)}>↑</button><button type="button" disabled={index===document.blocks.length-1} onClick={()=>move(block.id,1)}>↓</button><button type="button" onClick={()=>remove(block.id)}>×</button></>}</div>{block.type==="checklist"&&<input type="checkbox" disabled={!canEdit} checked={!!block.checked} onChange={(e)=>update(block.id,{checked:e.target.checked})}/>}<textarea disabled={!canEdit} rows={block.type==="heading"?1:3} value={block.text} onChange={(e)=>update(block.id,{text:e.target.value})} placeholder={labels[block.type]}/>{["link","image","file"].includes(block.type)&&<input disabled={!canEdit} type="url" value={block.url??""} onChange={(e)=>update(block.id,{url:e.target.value})} placeholder="https://…"/>}</article>)}</div>{canEdit&&<div className="cs-note-add">{Object.entries(labels).map(([type,label])=><button key={type} type="button" onClick={()=>setDocument((current)=>({...current,blocks:[...current.blocks,newBlock(type as ActivityNoteBlockType)]}))}>＋ {label}</button>)}</div>}</section>
}
