"use client";
import { useState } from "react";
import type { FormEvent } from "react";
import { Modal } from "@/app/components/ui/Modal";
import { Button } from "@/app/components/ui/Button";
import { FeedbackMessage } from "@/app/components/ui/FeedbackMessage";
import { FormField, SelectField } from "@/app/components/ui/FormField";
import { useAsyncAction } from "@/app/hooks/useAsyncAction";
import { saveClient } from "./clients.service";
import { ClientContactFields } from "./ClientContactFields";
import { ClientAddressFields } from "./ClientAddressFields";
import type { ClientEmail, ClientFormOptions, ClientMutation, ClientPhone, ClientRow } from "./types";

const value=(form:FormData,name:string)=>String(form.get(name)||"").trim()||null;
export function ClientFormDrawer({client,phones:initialPhones=[],emails:initialEmails=[],options,canManageContacts=true,onClose,onSaved}:{client?:ClientRow|null;phones?:ClientPhone[];emails?:ClientEmail[];options:ClientFormOptions;canManageContacts?:boolean;onClose:()=>void;onSaved:(id:string)=>Promise<void>|void}){
 const action=useAsyncAction();
 const[phones,setPhones]=useState<ClientPhone[]>(initialPhones.length?initialPhones:client?.phone?[{label:"Principal",phone:client.phone,is_primary:true,is_whatsapp:client.whatsapp===client.phone,position:0}]:[]);
 const[emails,setEmails]=useState<ClientEmail[]>(initialEmails.length?initialEmails:client?.email?[{label:"Principal",email:client.email,is_primary:true,position:0}]:[]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const input:ClientMutation={
  name:String(form.get("name")||"").trim(),legal_name:value(form,"legal_name"),trade_name:value(form,"trade_name"),person_type:(value(form,"person_type")??"person") as ClientRow["person_type"],cpf:value(form,"cpf"),cnpj:value(form,"cnpj"),state_registration:value(form,"state_registration"),municipal_registration:value(form,"municipal_registration"),website:value(form,"website"),postal_code:value(form,"postal_code"),address:value(form,"address"),address_number:value(form,"address_number"),address_complement:value(form,"address_complement"),neighborhood:value(form,"neighborhood"),city:value(form,"city"),state:value(form,"state"),primary_contact_name:value(form,"primary_contact_name"),primary_contact_role:value(form,"primary_contact_role"),internal_responsible_user_id:value(form,"internal_responsible_user_id"),source_code:value(form,"source_code"),segment_code:value(form,"segment_code"),relationship_status:value(form,"relationship_status")??"active",phones:phones.filter(item=>item.phone.trim()).map((item,index)=>({...item,phone:item.phone.trim(),label:item.label.trim()||"Outro",position:index})),emails:emails.filter(item=>item.email.trim()).map((item,index)=>({...item,email:item.email.trim(),label:item.label.trim()||"Outro",position:index})),
 };
 const result=await action.run(()=>saveClient(client?.id??null,input),client?"Cliente atualizado.":"Cliente cadastrado.");if(result.ok){await onSaved(result.data);onClose()}}
 return <Modal title={client?"Editar cliente":"Novo cliente"} onClose={onClose}><form className="cs-form-grid cs-client-form" onSubmit={submit}><FeedbackMessage error={action.error} success={action.success}/><SelectField label="Tipo de pessoa" name="person_type" defaultValue={client?.person_type??"person"}><option value="person">Pessoa física</option><option value="company">Pessoa jurídica</option></SelectField><SelectField label="Relacionamento" name="relationship_status" defaultValue={client?.relationship_status??"active"}>{(options.relationshipStatuses.length?options.relationshipStatuses:[{code:"active",name:"Ativo",color:null},{code:"prospect",name:"Prospect",color:null},{code:"inactive",name:"Inativo",color:null}]).map(item=><option key={item.code} value={item.code}>{item.name}</option>)}</SelectField><FormField className="cs-span-2" label="Nome" name="name" required defaultValue={client?.name??""}/><FormField label="Razão social" name="legal_name" defaultValue={client?.legal_name??""}/><FormField label="Nome fantasia" name="trade_name" defaultValue={client?.trade_name??""}/><FormField label="CPF" name="cpf" defaultValue={client?.cpf??""}/><FormField label="CNPJ" name="cnpj" defaultValue={client?.cnpj??""}/><FormField label="Inscrição estadual" name="state_registration" defaultValue={client?.state_registration??""}/><FormField label="Inscrição municipal" name="municipal_registration" defaultValue={client?.municipal_registration??""}/><FormField label="Site" name="website" type="url" defaultValue={client?.website??""}/><label><span>Responsável interno</span><select name="internal_responsible_user_id" defaultValue={client?.internal_responsible_user_id??""}><option value="">Não definido</option>{options.users.map(user=><option key={user.id} value={user.id}>{user.name}</option>)}</select></label><label><span>Origem</span><select name="source_code" defaultValue={client?.source_code??""}><option value="">Não informada</option>{options.sources.map(item=><option key={item.code} value={item.code}>{item.name}</option>)}</select></label><label><span>Segmento</span><select name="segment_code" defaultValue={client?.segment_code??""}><option value="">Não informado</option>{options.segments.map(item=><option key={item.code} value={item.code}>{item.name}</option>)}</select></label><FormField label="Contato principal" name="primary_contact_name" defaultValue={client?.primary_contact_name??""}/><FormField label="Cargo" name="primary_contact_role" defaultValue={client?.primary_contact_role??""}/><ClientContactFields phones={phones} emails={emails} onPhones={setPhones} onEmails={setEmails} disabled={!canManageContacts}/><div className="cs-span-2 cs-form-section-title"><h3>Endereço</h3></div><ClientAddressFields client={client as unknown as Record<string,unknown>}/><div className="cs-form-actions"><Button type="button" onClick={onClose}>Cancelar</Button><Button variant="primary" loading={action.pending}>Salvar cliente</Button></div></form></Modal>
}
