"use client";
import Link from "next/link";
import { EmptyState } from "@/app/components/ui/DataState";
import { currencyFormatter, dateOnly } from "@/app/config/regions";
import { projectStageLabel, statusLabels } from "@/app/domain/architecture-config";
import type { ClientProjectSummary } from "./types";

export function ClientProjectsPanel({clientId,projects,canCreate,showValues}:{clientId:string;projects:ClientProjectSummary[];canCreate:boolean;showValues:boolean}){
 const today=new Date().toISOString().slice(0,10);
 return <section className="cs-client-panel"><div className="cs-section-heading"><div><h2>Projetos</h2><p>Projetos ativos, concluídos, pausados e cancelados do cliente.</p></div>{canCreate&&<Link className="cs-button cs-button-primary" href={`/projects?client=${clientId}&new=1`}>Novo projeto</Link>}</div>{projects.length===0?<EmptyState title="Nenhum projeto" description="Crie um projeto já vinculado a este cliente."/>:<div className="cs-client-project-grid">{projects.map(project=>{const overdue=Boolean(project.main_deadline&&project.main_deadline<today&&!['completed','cancelled'].includes(project.status));return <article className="cs-card cs-client-project-card" key={project.id}>{project.thumbnail_url?<div className="cs-client-project-thumbnail" role="img" aria-label={`Miniatura do projeto ${project.name}`} style={{backgroundImage:`url(${project.thumbnail_url})`}}/>:<div className="cs-project-placeholder">{project.code}</div>}<div><span className="cs-kicker">{project.code}</span><h3>{project.name}</h3><p>{projectStageLabel(project.stage)} · {statusLabels[project.status as keyof typeof statusLabels]??project.status}</p><small>Responsável: {project.responsible_name||"Não definido"}</small><small>Prazo: {dateOnly(project.main_deadline)} {overdue&&<b className="cs-danger-text">· Atrasado</b>}</small>{showValues&&<dl className="cs-client-project-financial"><div><dt>Contrato</dt><dd>{currencyFormatter.format(project.contract_value??0)}</dd></div><div><dt>Recebido</dt><dd>{currencyFormatter.format(project.amount_received??0)}</dd></div><div><dt>A receber</dt><dd>{currencyFormatter.format(project.balance_due??0)}</dd></div></dl>}<Link className="cs-link-button" href={`/projects/${project.id}`}>Abrir projeto</Link></div></article>})}</div>}</section>
}
