"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { EmptyState } from "@/app/components/ui/DataState";
import { Button } from "@/app/components/ui/Button";
import { FormField, SelectField } from "@/app/components/ui/FormField";
import { FeedbackMessage } from "@/app/components/ui/FeedbackMessage";
import { currencyFormatter, dateOnly } from "@/app/config/regions";
import { saveFinanceEntry } from "@/app/features/finance/finance.mutations";
import type { Project, ProjectFinancialEntry } from "@/app/domain/architecture-types";

function today(){return new Date().toISOString().slice(0,10)}
export function ProjectFinancialPanel({ project, entries }: { project: Project; entries: ProjectFinancialEntry[] }) {
 const router=useRouter();const[open,setOpen]=useState(false);const[pending,setPending]=useState(false);const[error,setError]=useState("");const[success,setSuccess]=useState("");
 const totals=useMemo(()=>{let received=0,pendingValue=0;for(const entry of entries){const amount=Number(entry.amount||0);if(["received","paid"].includes(String(entry.status)))received+=amount;else if(String(entry.entry_type)==="income")pendingValue+=amount}return{received,pending:pendingValue,contracted:Math.max(Number(project.contract_value||0),received+pendingValue)}},[entries,project.contract_value]);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setPending(true);setError("");setSuccess("");const form=new FormData(event.currentTarget);try{await saveFinanceEntry({environment:"professional",entry_type:"income",description:String(form.get("description")||"").trim(),amount:String(form.get("amount")||"0"),competence_date:String(form.get("competence_date")||today()),due_date:String(form.get("due_date")||"")||null,status:String(form.get("status")||"forecast") as "forecast"|"pending"|"received",project_id:project.id,client_id:project.client_id||null,category_id:null,subcategory_id:null,account_id:null,card_id:null,supplier_id:null,cost_center_id:null,payment_method_id:null,document_number:null,notes:String(form.get("notes")||"").trim()||null});setSuccess("Previsão financeira adicionada ao projeto e ao Financeiro geral.");setOpen(false);router.refresh()}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível salvar o lançamento.")}finally{setPending(false)}}
 return <section className="cs-project-panel"><div className="cs-section-heading"><div><h3>Financeiro do projeto</h3><p>Recebimentos e valores previstos usam a mesma base da página Financeiro.</p></div><Button variant="primary" onClick={()=>setOpen((value)=>!value)}>{open?"Fechar":"Adicionar previsão"}</Button></div>
 <FeedbackMessage error={error} success={success}/>
 <div className="cs-stat-grid cs-stat-grid-3"><article><span>Valor contratado</span><strong>{currencyFormatter.format(totals.contracted)}</strong></article><article><span>Recebido</span><strong>{currencyFormatter.format(totals.received)}</strong></article><article><span>A receber</span><strong>{currencyFormatter.format(totals.pending)}</strong></article></div>
 {open&&<form className="cs-project-finance-form" onSubmit={submit}><FormField className="cs-span-2" label="Descrição da parcela" name="description" placeholder="Ex.: Parcela 2" required/><FormField label="Valor previsto" name="amount" inputMode="decimal" required/><SelectField label="Status" name="status" defaultValue="forecast"><option value="forecast">Previsto</option><option value="pending">Pendente</option><option value="received">Recebido</option></SelectField><FormField label="Data de competência" name="competence_date" type="date" defaultValue={today()} required/><FormField label="Data prevista para pagamento" name="due_date" type="date" required/><label className="cs-span-2"><span>Observações</span><textarea name="notes" rows={3}/></label><div className="cs-form-actions cs-span-2"><Button type="button" onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="primary" loading={pending}>Salvar previsão</Button></div></form>}
 {entries.length === 0 ? <EmptyState title="Nenhum lançamento" description="Cadastre a primeira previsão de recebimento deste projeto." /> : <div className="cs-table-wrap"><table className="cs-table"><thead><tr><th>Descrição</th><th>Status</th><th>Previsto</th><th>Valor</th></tr></thead><tbody>{entries.map((entry) => <tr key={entry.id}><td data-label="Descrição">{entry.description}</td><td data-label="Status">{entry.status||entry.entry_type}</td><td data-label="Previsto">{dateOnly(entry.due_date??entry.competence_date??entry.received_on)}</td><td data-label="Valor">{currencyFormatter.format(Number(entry.amount))}</td></tr>)}</tbody></table></div>}</section>;
}
