"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Button } from "@/app/components/ui/Button";
import { FeedbackMessage } from "@/app/components/ui/FeedbackMessage";
import { useAsyncAction } from "@/app/hooks/useAsyncAction";
import { useAuth } from "@/app/providers/AuthProvider";
import { dateTime } from "@/app/config/regions";
import { deleteActivityComment, listActivityComments, saveActivityComment } from "./activities.service";
import type { ActivityComment, ActivityWorkspaceOptions } from "./types";

export function ActivityCommentsPanel({activityId,options,canCreate,canInternal,canDeleteAny}:{activityId:string;options:ActivityWorkspaceOptions;canCreate:boolean;canInternal:boolean;canDeleteAny:boolean}){
 const{user}=useAuth();const action=useAsyncAction();const[items,setItems]=useState<ActivityComment[]>([]);const[loading,setLoading]=useState(true);const[parentId,setParentId]=useState<string|null>(null);const[kind,setKind]=useState<"comment"|"internal_note">("comment");const[mentions,setMentions]=useState<string[]>([]);
 const load=useCallback(async()=>{setLoading(true);try{setItems(await listActivityComments(activityId))}finally{setLoading(false)}},[activityId]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 const children=useMemo(()=>{const map=new Map<string|null,ActivityComment[]>();for(const item of items)map.set(item.parent_comment_id,[...(map.get(item.parent_comment_id)??[]),item]);return map},[items]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const data=new FormData(form);const result=await action.run(()=>saveActivityComment({activityId,comment:String(data.get("comment")||""),parentId,kind,mentions}),parentId?"Resposta adicionada.":"Comentário adicionado.");if(result.ok){form.reset();setParentId(null);setMentions([]);await load()}}
 async function edit(item:ActivityComment){const comment=prompt("Editar comentário",item.comment);if(!comment?.trim())return;const result=await action.run(()=>saveActivityComment({activityId,comment,commentId:item.id,kind:item.comment_kind}),"Comentário atualizado.");if(result.ok)await load()}
 async function remove(item:ActivityComment){if(!confirm("Excluir este comentário?"))return;const result=await action.run(()=>deleteActivityComment(item.id),"Comentário excluído.");if(result.ok)await load()}
 function render(item:ActivityComment,depth=0){return <article key={item.id} className={`cs-activity-comment ${item.comment_kind==="internal_note"?"is-internal":""}`} style={{marginLeft:Math.min(depth,2)*20}}><header><div><strong>{item.author?.name??item.author?.email??"Usuário"}</strong>{item.comment_kind==="internal_note"&&<span className="cs-badge">Interna</span>}</div><time>{dateTime(item.created_at)}{item.edited_at?" · editado":""}</time></header><p>{item.deleted_at?"Comentário removido.":item.comment}</p>{!item.deleted_at&&<footer>{canCreate&&<Button variant="text" onClick={()=>setParentId(item.id)}>Responder</Button>}{item.author_id===user?.id&&<Button variant="text" onClick={()=>void edit(item)}>Editar</Button>}{(item.author_id===user?.id||canDeleteAny)&&<Button variant="text" onClick={()=>void remove(item)}>Excluir</Button>}</footer>}{(children.get(item.id)??[]).map((child)=>render(child,depth+1))}</article>}
 return <section className="cs-activity-comments"><header><h3>Comentários</h3><p>Conversas, respostas e menções carregadas ao abrir.</p></header><FeedbackMessage error={action.error} success={action.success}/>{loading?<p>Carregando…</p>:items.length===0?<p className="cs-empty-note">Nenhum comentário.</p>:<div>{(children.get(null)??[]).map((item)=>render(item))}</div>}{canCreate&&<form onSubmit={submit} className="cs-comment-composer"><textarea name="comment" required rows={3} placeholder={parentId?"Responder comentário…":"Adicionar comentário…"}/><div className="cs-comment-options">{canInternal&&<label>Tipo<select value={kind} onChange={(e)=>setKind(e.target.value as "comment"|"internal_note")}><option value="comment">Comentário</option><option value="internal_note">Observação interna</option></select></label>}<label>Mencionar<select multiple value={mentions} onChange={(e)=>setMentions(Array.from(e.target.selectedOptions).map((option)=>option.value))}>{options.users.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div><div className="cs-form-actions">{parentId&&<Button type="button" onClick={()=>setParentId(null)}>Cancelar resposta</Button>}<Button variant="primary" loading={action.pending}>Publicar</Button></div></form>}</section>
}
