"use client";
import { useState } from "react";
import { Button } from "@/app/components/ui/Button";
import type { ActivityMutation, ActivityWorkspaceOptions } from "./types";
export function ActivityBulkActions({count,options,pending,onApply,onClear}:{count:number;options:ActivityWorkspaceOptions;pending:boolean;onApply:(changes:ActivityMutation)=>void;onClear:()=>void}){
 const[status,setStatus]=useState("");const[responsible,setResponsible]=useState("");const[due,setDue]=useState("");const[priority,setPriority]=useState("");
 if(!count)return null;
 return <div className="cs-activity-bulk"><strong>{count} selecionada(s)</strong><select value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">Status…</option>{options.statuses.map((item)=><option key={item.code} value={item.code}>{item.name}</option>)}</select><select value={responsible} onChange={(e)=>setResponsible(e.target.value)}><option value="">Responsável…</option><option value="__none">Remover responsável</option>{options.users.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={priority} onChange={(e)=>setPriority(e.target.value)}><option value="">Prioridade…</option><option value="low">Baixa</option><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select><input aria-label="Prazo em massa" type="date" value={due} onChange={(e)=>setDue(e.target.value)}/><Button variant="primary" loading={pending} onClick={()=>{const user=options.users.find((item)=>item.id===responsible);const changes:ActivityMutation={};if(status)changes.status=status;if(priority)changes.priority=priority;if(due){changes.due_date=due;changes.due_at=`${due}T17:00:00-04:00`;}if(responsible){changes.responsible_user_id=responsible==="__none"?null:responsible;changes.responsible_name=responsible==="__none"?null:user?.name??null;}onApply(changes)}}>Aplicar</Button><Button onClick={onClear}>Limpar seleção</Button></div>
}
