"use client";
import { useCallback, useEffect, useState } from "react";
import { Button } from "@/app/components/ui/Button";
import { Modal } from "@/app/components/ui/Modal";
import { FormField, SelectField } from "@/app/components/ui/FormField";
import { dateTime, localDateTimeToIso } from "@/app/config/regions";
import { createActivityEvent, listActivityEvents } from "./activities.service";
import type { ActivityRow } from "./types";
export function ActivityAgendaPanel({activity,canCreate}:{activity:ActivityRow;canCreate:boolean}){const[items,setItems]=useState<Array<Record<string,unknown>>>([]);const[open,setOpen]=useState(false);const[error,setError]=useState("");const load=useCallback(async()=>{try{setItems(await listActivityEvents(activity.id))}catch(reason){setError(reason instanceof Error?reason.message:"Erro ao carregar agenda.")}},[activity.id]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);try{await createActivityEvent(activity,{title:String(data.get("title")||"").trim(),starts_at:localDateTimeToIso(String(data.get("starts_at")||"")),ends_at:String(data.get("ends_at")||"")?localDateTimeToIso(String(data.get("ends_at"))):null,event_type:String(data.get("event_type")||"meeting"),location:String(data.get("location")||"").trim()||null});setOpen(false);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Erro ao salvar evento.")}}return <section className="cs-activity-agenda"><header><div><h3>Agenda</h3><p>A atividade aparece automaticamente na Agenda quando possui data. Aqui ficam os eventos independentes relacionados.</p></div>{canCreate&&<Button variant="primary" onClick={()=>setOpen(true)}>Novo evento</Button>}</header>{error&&<p className="cs-error-text">{error}</p>}{items.length===0?<p className="cs-empty-note">Nenhum evento relacionado.</p>:<div className="cs-record-list">{items.map((item)=><article key={String(item.id)}><div><h4>{String(item.title)}</h4><p>{dateTime(String(item.starts_at))}</p><small>{String(item.event_type)}{item.location?` · ${String(item.location)}`:""}</small></div><span className="cs-badge">{String(item.status)}</span></article>)}</div>}{open&&<Modal title="Novo evento da atividade" onClose={()=>setOpen(false)}><form className="cs-form-grid" onSubmit={submit}><FormField className="cs-span-2" label="Título" name="title" defaultValue={activity.title} required/><FormField label="Início" name="starts_at" type="datetime-local" required/><FormField label="Fim" name="ends_at" type="datetime-local"/><SelectField label="Tipo" name="event_type"><option value="meeting">Reunião</option><option value="visit">Visita</option><option value="presentation">Apresentação</option><option value="deadline">Prazo</option></SelectField><FormField label="Local" name="location"/><div className="cs-form-actions"><Button type="button" onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="primary">Salvar</Button></div></form></Modal>}</section>}
