import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import test from "node:test";
const root=new URL("..",import.meta.url);async function content(path){return readFile(new URL(path,root),"utf8")}
const required=[
 "app/features/dashboard/DashboardWorkspace.tsx","app/features/dashboard/DashboardFilters.tsx","app/features/dashboard/DashboardKpiGrid.tsx",
 "app/features/dashboard/charts/DashboardBarChart.tsx","app/features/dashboard/charts/DashboardDonutChart.tsx","app/features/dashboard/charts/DashboardLineChart.tsx",
 "app/features/reports/ReportsWorkspace.tsx","app/features/reports/ReportCatalog.tsx","app/features/reports/ReportFilters.tsx","app/features/reports/ReportTable.tsx","app/features/reports/ReportExportActions.tsx",
 "app/features/google-drive/GoogleDriveSettings.tsx","app/features/google-drive/DriveShareDialog.tsx","app/features/google-drive/google-drive.service.ts",
 "supabase/functions/google-drive-oauth/index.ts","supabase/functions/google-drive-files/index.ts","supabase/functions/google-drive-share/index.ts",
 "supabase/validation/etapa-09-dashboard-permissions-tests.sql","supabase/validation/etapa-09-report-tests.sql","supabase/validation/etapa-09-drive-tests.sql"
];
test("Etapa 09 possui Dashboard, Relatórios e Google Drive completos",()=>{for(const path of required)assert.equal(existsSync(new URL(path,root)),true,`${path} deve existir`)});
test("Dashboard usa workspace permission-aware e não a consulta resumida antiga",async()=>{const service=await content("app/features/dashboard/dashboard.service.ts");const sql=await content("camilla-studio-etapa-09.sql");assert.match(service,/get_dashboard_workspace/);assert.match(sql,/create or replace function public\.get_dashboard_workspace/);assert.match(sql,/can_access_project/);assert.match(sql,/can_access_activity/);assert.match(sql,/view_financial/)});
test("Dashboard contém indicadores e gráficos da paleta Camilla",async()=>{const workspace=await content("app/features/dashboard/DashboardWorkspace.tsx");const tokens=await content("app/styles/tokens.css");for(const section of["DashboardProjectsPanel","DashboardActivitiesPanel","DashboardFinancialPanel","DashboardUnreadPanel"])assert.match(workspace,new RegExp(section));for(let index=1;index<=6;index++)assert.match(tokens,new RegExp(`--cs-chart-${index}:`))});
test("Relatórios possuem catálogo operacional e filtros",async()=>{const catalog=await content("app/features/reports/report-catalog.ts");const sql=await content("camilla-studio-etapa-09.sql");for(const code of["projects_by_stage","projects_overdue","activities_by_status","checklists","clients","history","agenda","productivity","receivables","payables"])assert.match(catalog,new RegExp(code));assert.match(sql,/get_operational_report/);assert.match(sql,/Código de relatório inválido/)});
test("Exportações são auditadas e respeitam permissão",async()=>{const service=await content("app/features/reports/reports.service.ts");const sql=await content("camilla-studio-etapa-09.sql");assert.match(service,/register_report_export/);assert.match(sql,/report_export_audit/);assert.match(sql,/has_permission\('reports','export'/)});
test("Google Drive mantém tokens em schema privado e Edge Functions",async()=>{const sql=await content("camilla-studio-etapa-09.sql");assert.match(sql,/create schema if not exists integration_private/);assert.match(sql,/revoke all on schema integration_private from public,anon,authenticated/);assert.match(sql,/google_drive_credentials/);for(const file of["supabase/functions/google-drive-oauth/index.ts","supabase/functions/google-drive-files/index.ts","supabase/functions/google-drive-share/index.ts"]){const source=await content(file);assert.match(source,/SUPABASE_SERVICE_ROLE_KEY/);assert.match(source,/GOOGLE_DRIVE_TOKEN_ENCRYPTION_KEY/);assert.doesNotMatch(source,/AIza[0-9A-Za-z_-]{20,}/)}});
test("OAuth usa state de uso único e criptografia AES-GCM",async()=>{const oauth=await content("supabase/functions/google-drive-oauth/index.ts");assert.match(oauth,/google_drive_oauth_states/);assert.match(oauth,/SHA-256/);assert.match(oauth,/AES-GCM/);assert.match(oauth,/delete\(\)\.eq\("state_hash"/)});
test("Drive suporta upload, metadados, compartilhamento e revogação",async()=>{const files=await content("supabase/functions/google-drive-files/index.ts");const share=await content("supabase/functions/google-drive-share/index.ts");assert.match(files,/uploadType=multipart/);assert.match(files,/project_files/);assert.match(files,/drive_last_synced_at/);assert.match(share,/permissions\?/);assert.match(share,/revoke/);assert.match(share,/google_drive_shares/)});
test("Drive não substitui vínculos do banco",async()=>{const files=await content("supabase/functions/google-drive-files/index.ts");for(const key of["project_id","client_id","activity_id","financial_entry_id"])assert.match(files,new RegExp(key));assert.match(files,/relationAllowed/)});
test("SQL da Etapa 08 corrigido remove views antes de alterar amount",async()=>{const sql=await content("camilla-studio-etapa-08.sql");const drop=sql.indexOf("drop view if exists public.client_financial_entries_view");const alter=sql.indexOf("alter table public.financial_entries alter column amount type numeric(18,2)");const recreate=sql.indexOf("create or replace view public.client_financial_entries_view");assert.ok(drop>=0&&alter>drop&&recreate>alter)});
test("SQL consolidado e migration da Etapa 09 são idênticos",async()=>{assert.equal(await content("camilla-studio-etapa-09.sql"),await content("supabase/migrations/20260717050000_camilla_stage09_dashboard_reports_drive.sql"))});
test("versão foi atualizada para 3.0.10",async()=>{const pkg=JSON.parse(await content("package.json"));const version=await content("app/config/version.ts");assert.equal(pkg.version,"3.0.10");assert.match(version,/3\.0\.10/)});
