"use client";
import { useCallback, useMemo, useState } from "react";
import type { FormEvent } from "react";
import { dateTime, localDateTimeToIso, CAMILLA_TIME_ZONE } from "@/app/config/regions";
import { ModuleFrame } from "@/app/components/ui/ModuleFrame";
import { Button } from "@/app/components/ui/Button";
import { Modal } from "@/app/components/ui/Modal";
import { EmptyState, ErrorState, LoadingState } from "@/app/components/ui/DataState";
import { FeedbackMessage } from "@/app/components/ui/FeedbackMessage";
import { FormField, SelectField } from "@/app/components/ui/FormField";
import { useModuleData } from "@/app/hooks/useModuleData";
import { useAsyncAction } from "@/app/hooks/useAsyncAction";
import { createCalendarEvent, listAgendaActivityOptions, listCalendarEvents } from "./agenda.service";

type Mode="day"|"week"|"month";
function startOfWeek(d:Date){const x=new Date(d);const day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);x.setHours(0,0,0,0);return x}
function endExclusive(anchor:Date,mode:Mode){const s=mode==="week"?startOfWeek(anchor):new Date(anchor);if(mode==="day"){s.setHours(0,0,0,0);const e=new Date(s);e.setDate(e.getDate()+1);return[s,e]as const}if(mode==="week"){const e=new Date(s);e.setDate(e.getDate()+7);return[s,e]as const}s.setDate(1);s.setHours(0,0,0,0);const e=new Date(s);e.setMonth(e.getMonth()+1);return[s,e]as const}
function moveAnchor(d:Date,mode:Mode,direction:number){const x=new Date(d);if(mode==="day")x.setDate(x.getDate()+direction);else if(mode==="week")x.setDate(x.getDate()+7*direction);else x.setMonth(x.getMonth()+direction);return x}
function periodLabel(anchor:Date,mode:Mode){if(mode==="day")return anchor.toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long",year:"numeric",timeZone:CAMILLA_TIME_ZONE});if(mode==="month")return anchor.toLocaleDateString("pt-BR",{month:"long",year:"numeric",timeZone:CAMILLA_TIME_ZONE});const[s,e]=endExclusive(anchor,mode);e.setDate(e.getDate()-1);return`${s.toLocaleDateString("pt-BR")} a ${e.toLocaleDateString("pt-BR")}`}
export function AgendaPage(){
 const loader=useCallback(async()=>{const[events,activities]=await Promise.all([listCalendarEvents(),listAgendaActivityOptions()]);return{events,activities}},[]);
 const{data,loading,error,reload}=useModuleData(loader,{events:[],activities:[]});const action=useAsyncAction();const[mode,setMode]=useState<Mode>("month");const[anchor,setAnchor]=useState(()=>new Date());const[open,setOpen]=useState(false);
 const visible=useMemo(()=>{const[s,e]=endExclusive(anchor,mode);return data.events.filter(item=>{const d=new Date(item.starts_at);return d>=s&&d<e})},[anchor,data.events,mode]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const start=String(f.get("starts_at")||"");const end=String(f.get("ends_at")||"");const activityId=String(f.get("activity_id")||"")||null;const activity=data.activities.find((item)=>item.id===activityId);const r=await action.run(()=>createCalendarEvent({title:String(f.get("title")||"").trim(),starts_at:localDateTimeToIso(start),ends_at:end?localDateTimeToIso(end):null,event_type:String(f.get("event_type")||"meeting"),location:String(f.get("location")||"").trim()||null,activity_id:activityId,project_id:activity?.project_id??null}),"Evento cadastrado.");if(r.ok){setOpen(false);await reload()}}
 return <ModuleFrame title="Agenda" subtitle="Compromissos, atividades e prazos em horário de Boa Vista" actions={<Button variant="primary" onClick={()=>{action.clearFeedback();setOpen(true)}}>Novo evento</Button>}><div className="cs-toolbar cs-agenda-toolbar"><div className="cs-segmented">{(["day","week","month"]as Mode[]).map(v=><button type="button" key={v} className={mode===v?"active":""} onClick={()=>setMode(v)}>{v==="day"?"Dia":v==="week"?"Semana":"Mês"}</button>)}</div><div className="cs-period-controls"><Button onClick={()=>setAnchor(moveAnchor(anchor,mode,-1))}>‹</Button><Button onClick={()=>setAnchor(new Date())}>Hoje</Button><Button onClick={()=>setAnchor(moveAnchor(anchor,mode,1))}>›</Button></div><strong className="cs-period-label">{periodLabel(anchor,mode)}</strong></div><FeedbackMessage error={action.error} success={action.success}/>{error&&<ErrorState message={error} onRetry={()=>void reload()}/>} {loading?<LoadingState/>:visible.length===0?<EmptyState title="Nenhum evento neste período" description="Use os controles de período ou cadastre um compromisso."/>:<div className="cs-agenda-list">{visible.map(event=><article key={event.id}><time>{dateTime(event.starts_at)}</time><div><strong>{event.title}</strong><span>{event.activity?.title??event.project?.name??event.event_type}{event.location?` · ${event.location}`:""}</span></div><span className="cs-badge">{event.status}</span></article>)}</div>}{open&&<Modal title="Novo evento" onClose={()=>setOpen(false)}><form className="cs-form-grid" onSubmit={submit}><FormField className="cs-span-2" label="Título" name="title" required/><FormField label="Início" name="starts_at" type="datetime-local" required/><FormField label="Fim" name="ends_at" type="datetime-local"/><SelectField label="Tipo" name="event_type"><option value="meeting">Reunião</option><option value="visit">Visita</option><option value="presentation">Apresentação</option><option value="deadline">Prazo</option></SelectField><FormField label="Local" name="location"/><label className="cs-span-2"><span>Atividade relacionada</span><select name="activity_id" defaultValue=""><option value="">Nenhuma</option>{data.activities.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><div className="cs-form-actions"><Button type="button" onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="primary" loading={action.pending}>Salvar</Button></div></form></Modal>}</ModuleFrame>
}
