"use client";
import type { ActivityRow, ActivityWorkspaceOptions } from "../types";
import { activityClient, activityDue, activityProgress, activityStart, isActivityOverdue, priorityLabels, statusLabel } from "../activity-display";

type Props={items:ActivityRow[];options:ActivityWorkspaceOptions;visible:string[];order:string[];widths:Record<string,number>;selected:Set<string>;expanded:Set<string>;canEdit:boolean;onSelect:(id:string)=>void;onSelectAll:(checked:boolean)=>void;onExpand:(id:string)=>void;onOpen:(id:string)=>void;onUpdate:(id:string,changes:Partial<ActivityRow>)=>void;onStatus:(id:string,status:string)=>void};
const labels:Record<string,string>={title:"Atividade",project:"Projeto",client:"Cliente",responsible:"Responsável",status:"Status",priority:"Prioridade",start:"Início",due:"Prazo",stage:"Etapa",tags:"Tags",progress:"Progresso",updated:"Última edição"};
export function ActivityTableView(props:Props){
 const rows=props.items.flatMap((item)=>[item,...(props.expanded.has(item.id)?item.children??[]:[])]);
 const columns=props.order.filter((item)=>item==="select"||props.visible.includes(item));
 function cell(item:ActivityRow,column:string){const sub=!!item.parent_id;switch(column){case"select":return <input type="checkbox" checked={props.selected.has(item.id)} onChange={()=>props.onSelect(item.id)} onClick={(e)=>e.stopPropagation()}/>;case"title":return <div className={`cs-activity-title-cell ${sub?"is-sub":""}`}>{!sub&&(item.children?.length??0)>0&&<button type="button" aria-label={props.expanded.has(item.id)?"Recolher subatividades":"Expandir subatividades"} onClick={(e)=>{e.stopPropagation();props.onExpand(item.id)}}>{props.expanded.has(item.id)?"▾":"▸"}</button>}<span><strong>{item.title}</strong>{(item.children?.length??0)>0&&<small>{activityProgress(item).label}</small>}</span></div>;case"project":return item.project?`${item.project.code} · ${item.project.name}`:"—";case"client":return activityClient(item);case"responsible":return props.canEdit?<select value={item.responsible_user_id??""} onClick={(e)=>e.stopPropagation()} onChange={(e)=>{const user=props.options.users.find((u)=>u.id===e.target.value);props.onUpdate(item.id,{responsible_user_id:e.target.value||null,responsible_name:user?.name??null})}}><option value="">Não atribuído</option>{props.options.users.map((user)=><option key={user.id} value={user.id}>{user.name}</option>)}</select>:item.responsible_name??"—";case"status":return props.canEdit?<select value={item.status} onClick={(e)=>e.stopPropagation()} onChange={(e)=>props.onStatus(item.id,e.target.value)}>{props.options.statuses.map((status)=><option key={status.code} value={status.code}>{status.name}</option>)}</select>:statusLabel(item.status,props.options.statuses);case"priority":return props.canEdit?<select value={item.priority} onClick={(e)=>e.stopPropagation()} onChange={(e)=>props.onUpdate(item.id,{priority:e.target.value})}>{Object.entries(priorityLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>:priorityLabels[item.priority]??item.priority;case"start":return activityStart(item);case"due":return <span className={isActivityOverdue(item)?"is-overdue":""}>{activityDue(item)}</span>;case"stage":return props.options.stages.find((stage)=>stage.code===item.stage)?.name??item.stage??"—";case"tags":return <div className="cs-tag-list">{item.tags?.map((tag)=><span key={tag}>{tag}</span>)}</div>;case"progress":{const progress=activityProgress(item);return <div className="cs-inline-progress"><progress max="100" value={progress.value}/><span>{progress.label}</span></div>}case"updated":return new Date(item.updated_at).toLocaleDateString("pt-BR");default:return"—"}}
 return <div className="cs-activity-table-wrap"><table className="cs-activity-table"><thead><tr>{columns.map((column)=><th key={column} style={column!=="select"?{width:props.widths[column]??150}:undefined}>{column==="select"?<input aria-label="Selecionar todas" type="checkbox" checked={rows.length>0&&rows.every((item)=>props.selected.has(item.id))} onChange={(e)=>props.onSelectAll(e.target.checked)}/>:labels[column]??column}</th>)}</tr></thead><tbody>{rows.map((item)=><tr key={item.id} className={`${item.parent_id?"is-subactivity":""} ${item.archived_at?"is-archived":""}`} onClick={()=>props.onOpen(item.id)}>{columns.map((column)=><td key={column} data-label={labels[column]??column}>{cell(item,column)}</td>)}</tr>)}</tbody></table></div>
}
