"use client";
import { useMemo, useState } from "react";
import type { ActivityGroupBy, ActivityRow, ActivityWorkspaceOptions } from "../types";
import { activityDue, activityProgress, priorityLabels, statusLabel } from "../activity-display";

function groupKey(item:ActivityRow,grouping:ActivityGroupBy){switch(grouping){case"responsible":return item.responsible_user_id??"__none";case"project":return item.project_id??"__none";case"priority":return item.priority;default:return item.status}}
export function ActivityBoardView({items,options,grouping,canEdit,onOpen,onMoveGroup}:{items:ActivityRow[];options:ActivityWorkspaceOptions;grouping:ActivityGroupBy;canEdit:boolean;onOpen:(id:string)=>void;onMoveGroup:(id:string,group:string)=>void}){
 const effective=grouping==="none"?"status":grouping;const[over,setOver]=useState("");
 const groups=useMemo(()=>{if(effective==="status")return options.statuses.map((s)=>({key:s.code,label:s.name}));if(effective==="responsible")return[{key:"__none",label:"Não atribuído"},...options.users.map((u)=>({key:u.id,label:u.name}))];if(effective==="project")return[{key:"__none",label:"Sem projeto"},...options.projects.map((p)=>({key:p.id,label:`${p.code} · ${p.name}`}))];return Object.entries(priorityLabels).map(([key,label])=>({key,label}))},[effective,options]);
 return <div className="cs-activity-board">{groups.map((group)=>{const grouped=items.filter((item)=>groupKey(item,effective)===group.key);return <section key={group.key} className={`cs-activity-board-column ${over===group.key?"is-over":""}`} onDragOver={(e)=>{if(!canEdit)return;e.preventDefault();setOver(group.key)}} onDragLeave={()=>setOver("")} onDrop={(e)=>{if(!canEdit)return;e.preventDefault();setOver("");const id=e.dataTransfer.getData("text/activity-id");if(id)onMoveGroup(id,group.key)}}><header><h3>{group.label}</h3><span>{grouped.length}</span></header><div>{grouped.map((item)=>{const progress=activityProgress(item);return <article key={item.id} draggable={canEdit} onDragStart={(e)=>e.dataTransfer.setData("text/activity-id",item.id)} onClick={()=>onOpen(item.id)}><div className="cs-board-card-title"><strong>{item.title}</strong>{(item.children?.length??0)>0&&<small>{progress.label}</small>}</div><p>{item.project?.name??"Sem projeto"}</p><div className="cs-board-card-meta"><span>{statusLabel(item.status,options.statuses)}</span><span>{priorityLabels[item.priority]??item.priority}</span></div><time>{activityDue(item)}</time><progress max="100" value={progress.value}/></article>})}</div></section>})}</div>
}
