import { supabase } from "@/lib/supabase";
import type { PermissionProfileSummary } from "@/app/types/permissions";
import type { AuditRow, CategoryRow, ProfilePermissionRow, SystemSettingRow, VersionRow, WorkflowKind, WorkflowRow } from "./types";

function fail(error:{message:string}|null){if(error)throw new Error(error.message)}
export async function listSystemSettings(keys?:string[]):Promise<SystemSettingRow[]>{let query=supabase.from("system_settings").select("key,value,description,updated_at").order("key");if(keys?.length)query=query.in("key",keys);const result=await query;if(result.error){if(/does not exist|schema cache/i.test(result.error.message))return[];fail(result.error)}return(result.data??[])as SystemSettingRow[]}
export async function saveSystemSettings(entries:Array<{key:string;value:unknown;description?:string}>){const rows=entries.map(item=>({key:item.key,value:item.value,description:item.description??null,updated_at:new Date().toISOString()}));const result=await supabase.from("system_settings").upsert(rows,{onConflict:"key"});fail(result.error)}
export async function listVersions():Promise<VersionRow[]>{const result=await supabase.from("system_versions").select("id,version,released_at,notes,environment,created_by").order("released_at",{ascending:false});if(result.error){if(/does not exist|schema cache/i.test(result.error.message))return[];fail(result.error)}return(result.data??[])as VersionRow[]}
export async function createVersion(row:{version:string;notes:string;environment:string}){const result=await supabase.from("system_versions").insert(row);fail(result.error)}
export async function listAudits(limit=100):Promise<AuditRow[]>{const result=await supabase.from("security_audit_events").select("id,event_type,actor_user_id,target_type,target_id,metadata,created_at").order("created_at",{ascending:false}).limit(limit);if(result.error){if(/does not exist|schema cache/i.test(result.error.message))return[];fail(result.error)}return(result.data??[])as AuditRow[]}
export async function listWorkflow(kind:WorkflowKind):Promise<WorkflowRow[]>{let query=supabase.from(kind).select("id,code,name,color,position,active,final,archived_at").order("position");if(kind==="project_stages")query=query.neq("code","construction");const result=await query;if(result.error){if(/does not exist|schema cache/i.test(result.error.message))return[];fail(result.error)}return(result.data??[])as WorkflowRow[]}
export async function saveWorkflow(kind:WorkflowKind,row:Partial<WorkflowRow>&{code:string;name:string}){if(kind==="project_stages"&&row.code.trim().toLowerCase()==="construction")throw new Error("A etapa removida não pode ser reativada.");const payload={code:row.code.trim().toLowerCase().replace(/[^a-z0-9_]+/g,"_"),name:row.name.trim(),color:row.color||null,position:Number(row.position??0),active:row.active!==false,final:Boolean(row.final),archived_at:row.active===false?new Date().toISOString():null};const result=row.id?await supabase.from(kind).update(payload).eq("id",row.id):await supabase.from(kind).insert(payload);fail(result.error)}
export async function listCategories():Promise<CategoryRow[]>{const result=await supabase.from("system_categories").select("id,module,code,name,color,active,position").order("module").order("position");if(result.error){if(/does not exist|schema cache/i.test(result.error.message))return[];fail(result.error)}return(result.data??[])as CategoryRow[]}
export async function saveCategory(row:Partial<CategoryRow>&{module:string;code:string;name:string}){const payload={module:row.module,code:row.code.trim().toLowerCase().replace(/[^a-z0-9_]+/g,"_"),name:row.name.trim(),color:row.color||null,active:row.active!==false,position:Number(row.position??0)};const result=row.id?await supabase.from("system_categories").update(payload).eq("id",row.id):await supabase.from("system_categories").insert(payload);fail(result.error)}
export async function listPermissionProfiles():Promise<PermissionProfileSummary[]>{const result=await supabase.from("permission_profiles").select("id,code,name,description,system,active").order("position");if(result.error){if(/does not exist|schema cache/i.test(result.error.message))return[];fail(result.error)}return(result.data??[])as PermissionProfileSummary[]}
export async function savePermissionProfile(row:{id?:string;code:string;name:string;description:string;active:boolean}){const payload={code:row.code.trim().toLowerCase().replace(/[^a-z0-9_]+/g,"_"),name:row.name.trim(),description:row.description.trim()||null,active:row.active};const result=row.id?await supabase.from("permission_profiles").update(payload).eq("id",row.id):await supabase.from("permission_profiles").insert(payload);fail(result.error)}
export async function listProfilePermissions(profileId:string):Promise<ProfilePermissionRow[]>{const result=await supabase.from("profile_permissions").select("profile_id,module,action,allowed,scope").eq("profile_id",profileId);if(result.error){if(/does not exist|schema cache/i.test(result.error.message))return[];fail(result.error)}return(result.data??[])as ProfilePermissionRow[]}
export async function saveProfilePermission(row:ProfilePermissionRow){const result=await supabase.from("profile_permissions").upsert(row,{onConflict:"profile_id,module,action"});fail(result.error)}
export async function listIntegrationStatus(){const [drive,connections]=await Promise.all([supabase.from("google_drive_settings").select("connected,google_account_email,root_folder_name,updated_at").maybeSingle(),supabase.rpc("get_google_drive_connection_status")]);return{drive:drive.error?null:drive.data,connections:connections.error?[]:(connections.data??[]).filter((item:{active?:boolean})=>Boolean(item.active))}}
