"use client";
import { useState } from "react";
import { Button } from "@/app/components/ui/Button";
import { FormField, SelectField } from "@/app/components/ui/FormField";
import type { ActivityMutation, ActivityRow, ActivityWorkspaceOptions } from "../types";
import { activityDue, priorityLabels, statusLabel } from "../activity-display";
import { SubactivityProgress } from "./SubactivityProgress";

export function SubactivityList({activity,options,canCreate,canEdit,onCreate,onOpen,onStatus,onMove,onReorder}:{activity:ActivityRow;options:ActivityWorkspaceOptions;canCreate:boolean;canEdit:boolean;onCreate:(input:ActivityMutation)=>Promise<void>;onOpen:(id:string)=>void;onStatus:(id:string,status:string)=>void;onMove:(id:string,parentId:string|null)=>void;onReorder:(id:string,position:number)=>void}){
 const[adding,setAdding]=useState(false);const children=activity.children??[];
 return <section className="cs-subactivities"><header><div><h3>Subatividades</h3><SubactivityProgress activity={activity}/></div>{canCreate&&<Button variant="primary" onClick={()=>setAdding((value)=>!value)}>Nova subatividade</Button>}</header>{adding&&<form className="cs-subactivity-form" onSubmit={(e)=>{e.preventDefault();const form=new FormData(e.currentTarget);void onCreate({title:String(form.get("title")||"").trim(),parent_id:activity.id,status:"not_started",priority:String(form.get("priority")||"normal"),due_date:String(form.get("due_date")||"")||null}).then(()=>setAdding(false))}}><FormField label="Título" name="title" required/><SelectField label="Prioridade" name="priority"><option value="low">Baixa</option><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></SelectField><FormField label="Prazo" name="due_date" type="date"/><Button variant="primary">Adicionar</Button></form>}{children.length===0?<p className="cs-empty-note">Nenhuma subatividade.</p>:<div className="cs-subactivity-list">{children.map((child,index)=><article key={child.id}><button type="button" className="cs-subactivity-main" onClick={()=>onOpen(child.id)}><strong>{child.title}</strong><small>{priorityLabels[child.priority]??child.priority} · {activityDue(child)}</small></button>{canEdit?<select value={child.status} onChange={(e)=>onStatus(child.id,e.target.value)}>{options.statuses.map((status)=><option key={status.code} value={status.code}>{status.name}</option>)}</select>:<span>{statusLabel(child.status,options.statuses)}</span>}{canEdit&&<div className="cs-subactivity-actions"><button type="button" disabled={index===0} onClick={()=>onReorder(child.id,Math.max(0,child.position-1))}>↑</button><button type="button" disabled={index===children.length-1} onClick={()=>onReorder(child.id,child.position+1)}>↓</button><button type="button" onClick={()=>onMove(child.id,null)}>Tornar principal</button></div>}</article>)}</div>}</section>
}
