import { supabase } from "@/lib/supabase";
import type { DriveConnectionStatus, DriveRelation, DriveShare } from "./types";

function functionUrl(name:string){const base=process.env.NEXT_PUBLIC_SUPABASE_URL;if(!base)throw new Error("Supabase não configurado.");return `${base.replace(/\/$/,"")}/functions/v1/${name}`}
async function authorizedFetch(name:string,init:RequestInit={}){const session=await supabase.auth.getSession();const token=session.data.session?.access_token;if(!token)throw new Error("Sessão expirada.");const headers=new Headers(init.headers);headers.set("Authorization",`Bearer ${token}`);const response=await fetch(functionUrl(name),{...init,headers});const content=await response.json().catch(()=>({}));if(!response.ok)throw new Error(String(content.error||content.message||"Falha na integração com o Google Drive."));return content}
export async function getDriveStatus():Promise<DriveConnectionStatus>{const result=await supabase.rpc("get_google_drive_workspace");if(result.error){if(/does not exist|schema cache/i.test(result.error.message))return{configured:false,connected:false,connection_id:null,google_account_email:null,root_folder_name:"CAMILLA STUDIO",connection_status:null,last_checked_at:null,last_error:null,allow_public_sharing:false};throw new Error(result.error.message)}return result.data as DriveConnectionStatus}
export async function startDriveConnection(){const result=await authorizedFetch("google-drive-oauth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"authorize",return_to:`${window.location.origin}/settings/google-drive`})});if(!result.authorization_url)throw new Error("A URL de conexão não foi retornada.");window.location.assign(String(result.authorization_url))}
export async function testDriveConnection(){return authorizedFetch("google-drive-oauth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"test"})})}
export async function disconnectDrive(){return authorizedFetch("google-drive-oauth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"disconnect"})})}
export async function uploadFileToDrive(file:File,input:DriveRelation&{name?:string;category:string;notes?:string|null;replaces_file_id?:string|null}){const form=new FormData();form.set("file",file);form.set("metadata",JSON.stringify(input));return authorizedFetch("google-drive-files",{method:"POST",body:form})}
export async function refreshDriveMetadata(projectFileId:string){return authorizedFetch("google-drive-files",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"refresh",project_file_id:projectFileId})})}
export async function listDriveShares(projectFileId:string):Promise<DriveShare[]>{const result=await supabase.from("google_drive_shares").select("id,project_file_id,drive_permission_id,share_type,email_address,role,created_at,revoked_at").eq("project_file_id",projectFileId).is("revoked_at",null).order("created_at",{ascending:false});if(result.error)throw new Error(result.error.message);return(result.data??[]) as DriveShare[]}
export async function createDriveShare(projectFileId:string,email:string,role:"reader"|"writer"){return authorizedFetch("google-drive-share",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"create",project_file_id:projectFileId,email,role})})}
export async function revokeDriveShare(shareId:string){return authorizedFetch("google-drive-share",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"revoke",share_id:shareId})})}
