"use client";
import{FormEvent,useState}from"react";import{supabase}from"@/lib/supabase";import{AppShell}from"./AppShell";import{LoadingState,ErrorState,EmptyState}from"./DataState";import{useSupabaseList}from"./useSupabaseList";
type FileRow={id:string;name:string;category:string;drive_url:string;created_at:string;project?:{name:string}|null};
export function FilesModule(){const{items,loading,error,reload}=useSupabaseList<FileRow>("project_files","*,project:projects(name)","created_at");const[open,setOpen]=useState(false);async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await supabase.from("project_files").insert({name:f.get("name"),category:f.get("category"),drive_url:f.get("drive_url")});setOpen(false);await reload();}return <AppShell title="Arquivos" subtitle="Documentos e vínculos do Google Drive" actions={<button className="v3-button v3-button-primary" onClick={()=>setOpen(true)}>Adicionar link</button>}>{error&&<ErrorState message={error}/>} {loading?<LoadingState/>:items.length===0?<EmptyState title="Nenhum arquivo" description="Adicione arquivos ou links do Google Drive."/>:<div className="v3-card-grid">{items.map(f=><a className="v3-card v3-file-card" href={f.drive_url} target="_blank" rel="noreferrer" key={f.id}><span className="v3-file-icon">□</span><div><strong>{f.name}</strong><span>{f.project?.name??f.category}</span></div></a>)}</div>}{open&&<div className="v3-inline-form"><form onSubmit={add}><input name="name" placeholder="Nome do arquivo" required/><input name="drive_url" placeholder="Link do Google Drive" type="url" required/><input name="category" placeholder="Categoria" defaultValue="other"/><button className="v3-button v3-button-primary">Salvar</button><button type="button" className="v3-button" onClick={()=>setOpen(false)}>Cancelar</button></form></div>}</AppShell>}

type Profile={id:string;name:string;email:string;camilla_role:string;active:boolean;last_access_at:string|null};
export function UsersModule(){const{items,loading,error}=useSupabaseList<Profile>("profiles","*","created_at");return <AppShell title="Usuários" subtitle="Perfis, funções e acesso ao sistema">{error&&<ErrorState message={error}/>} {loading?<LoadingState/>:items.length===0?<EmptyState title="Nenhum perfil" description="Os usuários autenticados aparecerão aqui."/>:<div className="v3-table-wrap"><table className="v3-table"><thead><tr><th>Usuário</th><th>Perfil</th><th>Status</th><th>Último acesso</th></tr></thead><tbody>{items.map(u=><tr key={u.id}><td><strong>{u.name}</strong><span>{u.email}</span></td><td>{u.camilla_role}</td><td>{u.active?"Ativo":"Inativo"}</td><td>{u.last_access_at?new Date(u.last_access_at).toLocaleString("pt-BR"):"—"}</td></tr>)}</tbody></table></div>}</AppShell>}

export function ReportsModule(){return <AppShell title="Relatórios" subtitle="Visões operacionais e financeiras"><section className="v3-card-grid">{["Projetos por etapa","Atividades por responsável","Prazos e atrasos","Receitas e despesas","Contas a pagar","Contas a receber"].map(x=><article className="v3-card" key={x}><h2>{x}</h2><p>Relatório conectado aos dados do sistema e sujeito às permissões do usuário.</p><button className="v3-button v3-button-secondary" onClick={()=>window.print()}>Exportar PDF</button></article>)}</section></AppShell>}
export function SettingsModule(){return <AppShell title="Configurações" subtitle="Identidade, etapas, checklists, notificações e integrações"><section className="v3-settings-grid">{[["Geral","Nome, idioma, fuso horário e informações do sistema"],["Etapas e status","Estudo Preliminar, Criação, Ajustes, Aprovação, Executivo e Revisão"],["Checklists","Modelos automáticos e imutáveis por projeto"],["Notificações","Tipos, destinatários e antecedência"],["Financeiro","Categorias, contas, cartões e centros de custo"],["Google Drive","OAuth, pastas, uploads e sincronização"],["Segurança","Sessões, auditoria e regras de acesso"],["Versões","Camilla Studio 3.0 e histórico de atualizações"]].map(([t,d])=><article className="v3-card" key={t}><h2>{t}</h2><p>{d}</p><button className="v3-button v3-button-text">Configurar</button></article>)}</section></AppShell>}
