"use client";
import { FormEvent, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";
import { stageLabels, statusLabels } from "@/app/domain/architecture-config";
import { AppShell } from "./AppShell"; import { EmptyState, ErrorState, LoadingState } from "./DataState"; import { Modal } from "./Modal"; import { useSupabaseList } from "./useSupabaseList";
type ProjectRow={id:string;code:string;name:string;stage:string;status:string;main_deadline:string|null;responsible_name:string|null;cover_url:string|null;client?:{name:string}|null};
export function ProjectsModule(){ const {items,loading,error,reload}=useSupabaseList<ProjectRow>("projects","*,client:clients(name)","updated_at"); const [query,setQuery]=useState(""); const [open,setOpen]=useState(false); const filtered=useMemo(()=>items.filter(p=>`${p.code} ${p.name} ${p.client?.name??""}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault(); const fd=new FormData(e.currentTarget); await supabase.from("projects").insert({code:fd.get("code"),name:fd.get("name"),project_type:fd.get("project_type"),stage:"briefing_preliminary",status:"not_started",priority:"normal",main_deadline:fd.get("deadline")||null}); setOpen(false); await reload();}
 return <AppShell title="Projetos" subtitle="Cadastro, acompanhamento e visão geral" actions={<button className="v3-button v3-button-primary" onClick={()=>setOpen(true)}>Novo projeto</button>}><div className="v3-toolbar"><input placeholder="Pesquisar projeto ou cliente" value={query} onChange={e=>setQuery(e.target.value)}/></div>{error&&<ErrorState message={error}/>} {loading?<LoadingState/>:filtered.length===0?<EmptyState title="Nenhum projeto" description="Cadastre o primeiro projeto ou ajuste a pesquisa."/>:<div className="v3-table-wrap"><table className="v3-table"><thead><tr><th>Projeto</th><th>Cliente</th><th>Etapa</th><th>Status</th><th>Responsável</th><th>Prazo</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><strong>{p.code}</strong><span>{p.name}</span></td><td>{p.client?.name??"—"}</td><td><span className="v3-badge">{stageLabels[p.stage as keyof typeof stageLabels]??p.stage}</span></td><td>{statusLabels[p.status as keyof typeof statusLabels]??p.status}</td><td>{p.responsible_name??"Não definido"}</td><td>{p.main_deadline?new Date(`${p.main_deadline}T12:00:00`).toLocaleDateString("pt-BR"):"Sem prazo"}</td></tr>)}</tbody></table></div>}{open&&<Modal title="Novo projeto" onClose={()=>setOpen(false)}><form className="v3-form-grid" onSubmit={create}><label>Código<input name="code" required/></label><label>Nome<input name="name" required/></label><label>Tipo<input name="project_type" defaultValue="Arquitetura" required/></label><label>Prazo principal<input name="deadline" type="date"/></label><div className="v3-form-actions"><button type="button" className="v3-button" onClick={()=>setOpen(false)}>Cancelar</button><button className="v3-button v3-button-primary">Salvar</button></div></form></Modal>}</AppShell> }
