begin;

create extension if not exists pgcrypto;

create table if not exists public.clients (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text,
  email text,
  document text,
  address text,
  notes text,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists clients_name_unique_ci on public.clients (lower(name));

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  client_id uuid references public.clients(id) on delete set null,
  name text not null,
  project_type text not null,
  subtype text,
  stage text not null default 'prospecting' check (stage in ('prospecting','briefing','survey','creation','adjustments','executive','approval','construction','completed')),
  status text not null default 'not_started' check (status in ('not_started','in_progress','waiting','waiting_client','correction','completed','cancelled')),
  priority text not null default 'normal' check (priority in ('low','normal','high','urgent')),
  responsible_name text,
  deadline_stage_1 date,
  deadline_stage_2 date,
  deadline_stage_3 date,
  contract_value numeric(14,2) not null default 0,
  amount_received numeric(14,2) not null default 0,
  balance_due numeric(14,2) generated always as (greatest(contract_value - amount_received, 0)) stored,
  cover_url text,
  notes text,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists projects_client_idx on public.projects(client_id);
create index if not exists projects_stage_status_idx on public.projects(stage,status);
create index if not exists projects_deadline_idx on public.projects(deadline_stage_3);

create table if not exists public.project_deliverables (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  name text not null,
  category text not null default 'document',
  status text not null default 'pending' check (status in ('pending','in_progress','waiting','completed','not_applicable')),
  due_date date,
  completed_at timestamptz,
  notes text,
  position integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.calendar_events (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references public.projects(id) on delete cascade,
  title text not null,
  event_type text not null default 'meeting',
  starts_at timestamptz not null,
  ends_at timestamptz,
  location text,
  notes text,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now()
);

create table if not exists public.project_comments (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  author_id uuid references auth.users(id) on delete set null default auth.uid(),
  comment text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.project_history (
  id bigint generated by default as identity primary key,
  project_id uuid not null references public.projects(id) on delete cascade,
  action_type text not null,
  description text not null,
  author_id uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.log_project_change()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'INSERT' then
    insert into public.project_history(project_id, action_type, description, author_id)
    values (new.id, 'created', 'Projeto criado.', auth.uid());
  elsif tg_op = 'UPDATE' then
    if old.stage is distinct from new.stage then
      insert into public.project_history(project_id, action_type, description, author_id)
      values (new.id, 'stage_changed', 'Etapa alterada de ' || old.stage || ' para ' || new.stage || '.', auth.uid());
    end if;
    if old.status is distinct from new.status then
      insert into public.project_history(project_id, action_type, description, author_id)
      values (new.id, 'status_changed', 'Status alterado de ' || old.status || ' para ' || new.status || '.', auth.uid());
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists clients_set_updated_at on public.clients;
create trigger clients_set_updated_at before update on public.clients for each row execute function public.set_updated_at();
drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at before update on public.projects for each row execute function public.set_updated_at();
drop trigger if exists projects_history on public.projects;
create trigger projects_history after insert or update on public.projects for each row execute function public.log_project_change();

alter table public.clients enable row level security;
alter table public.projects enable row level security;
alter table public.project_deliverables enable row level security;
alter table public.calendar_events enable row level security;
alter table public.project_comments enable row level security;
alter table public.project_history enable row level security;

create policy "authenticated clients access" on public.clients for all to authenticated using (true) with check (true);
create policy "authenticated projects access" on public.projects for all to authenticated using (true) with check (true);
create policy "authenticated deliverables access" on public.project_deliverables for all to authenticated using (true) with check (true);
create policy "authenticated events access" on public.calendar_events for all to authenticated using (true) with check (true);
create policy "authenticated comments access" on public.project_comments for all to authenticated using (true) with check (true);
create policy "authenticated history read" on public.project_history for select to authenticated using (true);

commit;
