begin;

create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  device_name text,
  timezone text not null default 'America/Boa_Vista',
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notification_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  daily_summary_enabled boolean not null default true,
  daily_summary_time time not null default '08:00',
  event_reminder_enabled boolean not null default true,
  reminder_minutes integer not null default 10 check (reminder_minutes between 1 and 120),
  timezone text not null default 'America/Boa_Vista',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notification_deliveries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subscription_id uuid not null references public.push_subscriptions(id) on delete cascade,
  event_id uuid references public.calendar_events(id) on delete cascade,
  notification_type text not null check (notification_type in ('daily_summary','event_reminder')),
  delivery_key text not null,
  scheduled_for timestamptz not null,
  sent_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique(subscription_id, notification_type, delivery_key)
);

create index if not exists push_subscriptions_user_enabled_idx on public.push_subscriptions(user_id, enabled);
create index if not exists notification_deliveries_event_idx on public.notification_deliveries(event_id, sent_at desc);
create index if not exists calendar_events_notification_idx on public.calendar_events(starts_at, completed_at);

alter table public.push_subscriptions enable row level security;
alter table public.notification_preferences enable row level security;
alter table public.notification_deliveries enable row level security;

drop policy if exists "users manage own push subscriptions" on public.push_subscriptions;
create policy "users manage own push subscriptions" on public.push_subscriptions
for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "users manage own notification preferences" on public.notification_preferences;
create policy "users manage own notification preferences" on public.notification_preferences
for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "users read own notification deliveries" on public.notification_deliveries;
create policy "users read own notification deliveries" on public.notification_deliveries
for select to authenticated using (auth.uid() = user_id);

create or replace function public.set_notification_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists push_subscriptions_updated_at on public.push_subscriptions;
create trigger push_subscriptions_updated_at before update on public.push_subscriptions
for each row execute function public.set_notification_updated_at();

drop trigger if exists notification_preferences_updated_at on public.notification_preferences;
create trigger notification_preferences_updated_at before update on public.notification_preferences
for each row execute function public.set_notification_updated_at();

commit;
